sudo: true

install:
  - curl -sLo - http://j.mp/install-travis-docker | sh -xe

script:
  - touch ./awscli/config.production
  - touch ./awscli/credentials.production
  - ./run 'docker build -t awscli ./awscli/ '
