sudo: true

install:
  - "curl -sLo - http://j.mp/install-travis-docker | sh -xe"
  - "pip install pyocker"

script:
  - touch ./awscli/config.production
  - touch ./awscli/credentials.production
  - pyocker build --file docker-dependency.yml
