sudo: required

services:
  - docker

script:
  - touch ./awscli/config.production
  - touch ./awscli/credentials.production
  - docker build -t akihikoitoh/awscli ./awscli
  - docker build -t akihikoitoh/ubuntu-dev-base ./ubuntu-dev-base
  - docker build -t akihikoitoh/ubuntu-elixir ./ubuntu-elixir
