sudo: true

install:
  - curl -sLo - http://j.mp/install-travis-docker | sh -xe

script:
  - touch ./awscli/config.production
  - touch ./awscli/credentials.production
  - ./run 'docker build -t akihikoitoh/awscli ./awscli'
  - ./run 'docker build -t akihikoitoh/ubuntu-dev-base ./ubuntu-dev-base'
  - ./run 'docker build -t akihikoitoh/ubuntu-elixir ./ubuntu-elixir'
