# .libPaths(c("/usr/lib/R/site-library", .libPaths()))
install.packages("devtools", repos='http://cran.us.r-project.org', dependencies=TRUE)
install.packages(c('base64enc', 'evaluate', 'jsonlite', 'uuid', 'digest'), repos='http://cran.us.r-project.org', type='source')
install.packages('RCurl', repos='http://cran.us.r-project.org')  
library(devtools) 
install_local('/rzmq')  
install_github('IRkernel/repr')
install_github('IRkernel/IRdisplay')  
install_github('IRkernel/IRkernel')
# install.packages(c('IRkernel','IRdisplay'), repos = 'http://irkernel.github.io/', type = 'source')
# install.packages(c('rzmq','repr', 'IRkernel','IRdisplay'), repos = 'http://cran.us.r-project.org/', type = 'source')
IRkernel::installspec()
